version: '2.1'

services:
  go-blog:
    image: postgres:9.6.3
    restart: always
    ports:
      - "5432:5432"
    volumes: ["./testdata/:/docker-entrypoint-initdb.d/"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=go_blog

  api:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/github.com/deepinbytes/go-blog
    depends_on:
        go-blog:
          condition: service_healthy
    links:
      - go-blog
    environment:
      WAIT_HOSTS: go-blog:5433


